/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package assignmentexample;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;




/**
 * *
 *

 * @author hnd
 */
public class MainMenu extends javax.swing.JFrame {
    
  
    
    public MainMenu() {
       
        initComponents();
        UserSignUpPanel1.setVisible(false);
        addBagPannel.setVisible(false);
        viewBagpannel.setVisible(false);
        searchBagPannel.setVisible(false);
        
        
    }
    
    private void clearData(){
        bagNameBox.setText(null);
        categoryBox1.setSelectedItem(null);
        bagQtyBox.setText(null);
        PriceBox.setText(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UserSignUpPanel1 = new javax.swing.JLayeredPane();
        userFirstNameTextBox1 = new javax.swing.JTextField();
        userLastNameTextBox1 = new javax.swing.JTextField();
        usernameTextBox1 = new javax.swing.JTextField();
        passwordTextBox1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        confirmPasswordTextBox1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addNewUserButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        viewBagpannel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bagTable = new javax.swing.JTable();
        viewBagButton = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        addBagPannel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PriceBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bagQtyBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bagNameBox = new javax.swing.JTextField();
        addnewBagBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        categoryBox1 = new javax.swing.JComboBox<>();
        searchBagPannel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bagTable2 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        categoryBox2 = new javax.swing.JComboBox<>();
        seaarchBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        addNewUserMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addBag = new javax.swing.JMenuItem();
        viewBag = new javax.swing.JMenuItem();
        searchBag = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        userLastNameTextBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLastNameTextBox1ActionPerformed(evt);
            }
        });

        passwordTextBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextBox1ActionPerformed(evt);
            }
        });

        jLabel6.setText("First Name");

        jLabel7.setText("Last Name");

        jLabel8.setText("Username");

        jLabel9.setText("Password");

        jLabel10.setText("Confirm Password");

        addNewUserButton1.setText("Add New User");
        addNewUserButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserButton1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Add new user");

        UserSignUpPanel1.setLayer(userFirstNameTextBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(userLastNameTextBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(usernameTextBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(passwordTextBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(confirmPasswordTextBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(addNewUserButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        UserSignUpPanel1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout UserSignUpPanel1Layout = new javax.swing.GroupLayout(UserSignUpPanel1);
        UserSignUpPanel1.setLayout(UserSignUpPanel1Layout);
        UserSignUpPanel1Layout.setHorizontalGroup(
            UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                            .addComponent(userFirstNameTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(140, 140, 140))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserSignUpPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserSignUpPanel1Layout.createSequentialGroup()
                        .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                                .addComponent(userLastNameTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)))
                .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                        .addComponent(confirmPasswordTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                        .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(155, Short.MAX_VALUE))))
            .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(addNewUserButton1))
                    .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserSignUpPanel1Layout.setVerticalGroup(
            UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserSignUpPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userFirstNameTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(usernameTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userLastNameTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addNewUserButton1)
                    .addGroup(UserSignUpPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(confirmPasswordTextBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        bagTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bag Name", "Bag Category", "Bag Qty", "Bag Price"
            }
        ));
        jScrollPane1.setViewportView(bagTable);

        viewBagButton.setText("View Bag");
        viewBagButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBagButtonActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 102));
        jLabel12.setText("View Bag");

        javax.swing.GroupLayout viewBagpannelLayout = new javax.swing.GroupLayout(viewBagpannel);
        viewBagpannel.setLayout(viewBagpannelLayout);
        viewBagpannelLayout.setHorizontalGroup(
            viewBagpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBagpannelLayout.createSequentialGroup()
                .addGroup(viewBagpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(viewBagpannelLayout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewBagButton))
                    .addGroup(viewBagpannelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        viewBagpannelLayout.setVerticalGroup(
            viewBagpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewBagpannelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(viewBagpannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(viewBagButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setText("Bag Name");

        jLabel2.setText("Bag Category");

        PriceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("Bag Qty");

        jLabel4.setText("Bag Price");

        addnewBagBtn.setText("Add New Bag");
        addnewBagBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewBagBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 130, Short.MAX_VALUE)
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 102));
        jLabel11.setText("Add new Bag");

        categoryBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tote Bag", "Shoulder Bag ", "Bagpack", " " }));

        javax.swing.GroupLayout addBagPannelLayout = new javax.swing.GroupLayout(addBagPannel);
        addBagPannel.setLayout(addBagPannelLayout);
        addBagPannelLayout.setHorizontalGroup(
            addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBagPannelLayout.createSequentialGroup()
                .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBagPannelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2)
                        .addGap(281, 281, 281)
                        .addComponent(addnewBagBtn)
                        .addGap(223, 223, 223)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(addBagPannelLayout.createSequentialGroup()
                        .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addBagPannelLayout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(jLabel11))
                            .addGroup(addBagPannelLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel1)
                                .addGap(30, 30, 30)
                                .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(addBagPannelLayout.createSequentialGroup()
                                        .addComponent(bagNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bagQtyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(addBagPannelLayout.createSequentialGroup()
                                        .addComponent(categoryBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        addBagPannelLayout.setVerticalGroup(
            addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBagPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bagNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(bagQtyBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(categoryBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(PriceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(addBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addBagPannelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(addBagPannelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addnewBagBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        bagTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bag Name", "Bag Category", "Bag Prise", "Bag Qty"
            }
        ));
        jScrollPane2.setViewportView(bagTable2);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 102));
        jLabel13.setText("Search Bag");

        categoryBox2.setBackground(new java.awt.Color(204, 204, 204));
        categoryBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tote Bag", "Shoulder Bag", "Bagpack" }));
        categoryBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryBox2ActionPerformed(evt);
            }
        });

        seaarchBtn.setText("Search");
        seaarchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seaarchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchBagPannelLayout = new javax.swing.GroupLayout(searchBagPannel);
        searchBagPannel.setLayout(searchBagPannelLayout);
        searchBagPannelLayout.setHorizontalGroup(
            searchBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchBagPannelLayout.createSequentialGroup()
                .addGroup(searchBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchBagPannelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(searchBagPannelLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel13))
                    .addGroup(searchBagPannelLayout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(categoryBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seaarchBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        searchBagPannelLayout.setVerticalGroup(
            searchBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchBagPannelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchBagPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoryBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seaarchBtn))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jMenu1.setText("User Management");

        addNewUserMenuItem.setText("Add New User");
        addNewUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(addNewUserMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Item Management");

        addBag.setText("Add Bag");
        addBag.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBagActionPerformed(evt);
            }
        });
        jMenu2.add(addBag);

        viewBag.setText("View Bag");
        viewBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBagActionPerformed(evt);
            }
        });
        jMenu2.add(viewBag);

        searchBag.setText("Search Bag");
        searchBag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBagActionPerformed(evt);
            }
        });
        jMenu2.add(searchBag);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(viewBagpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(UserSignUpPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(addBagPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(searchBagPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(UserSignUpPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBagPannel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewBagpannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(searchBagPannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(766, 458));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private void DisplayUsers() {
        // Code to display users, e.g., in a table or list
        // For now, we'll just show a message as a placeholder
        JOptionPane.showMessageDialog(this, "Displaying all users (Functionality not yet implemented)");
    }


    private void addNewUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserMenuItemActionPerformed
        // TODO add your handling code here:
         UserSignUpPanel1.setVisible(true);
        addBagPannel.setVisible(false);
        viewBagpannel.setVisible(false);
        searchBagPannel.setVisible(false);
    }//GEN-LAST:event_addNewUserMenuItemActionPerformed

    private void addBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBagActionPerformed
        // TODO acdd your handling code here:
        addBagPannel.setVisible(true);
        UserSignUpPanel1.setVisible(false);
        viewBagpannel.setVisible(false);
        searchBagPannel.setVisible(false);
    }//GEN-LAST:event_addBagActionPerformed

    private void searchBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBagActionPerformed
        // TODO add your handling code here:
        addBagPannel.setVisible(false);
        UserSignUpPanel1.setVisible(false);
        viewBagpannel.setVisible(false);
        searchBagPannel.setVisible(true);
    }//GEN-LAST:event_searchBagActionPerformed

    private void addNewUserButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserButton1ActionPerformed
        // Retrieve values from input fields
    String username = usernameTextBox1.getText();
    String firstName = userFirstNameTextBox1.getText();
    String password = passwordTextBox1.getText();
    String lastName = userLastNameTextBox1.getText();
    String confirmPassword = confirmPasswordTextBox1.getText();
    
    // Check if passwords match
    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Passwords do not match.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Create new user object
    User newUser = new User();
    newUser.setFirstName(firstName);
    newUser.setLastName(lastName);
    newUser.setUserName(username);
    newUser.setPassword(password);

    // Add user using UserAppLogics
    UserAppLogics userAppLogics = new UserAppLogics();
    boolean isUserAdded = userAppLogics.AddNewUser(newUser);

    // Show success or error message
    if (isUserAdded) {
        JOptionPane.showMessageDialog(this, "User added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Failed to add user. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_addNewUserButton1ActionPerformed

    private void viewBagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBagActionPerformed
        // TODO add your handling code here
    addBagPannel.setVisible(false);
        UserSignUpPanel1.setVisible(false);
        viewBagpannel.setVisible(true);
        searchBagPannel.setVisible(false);
    }//GEN-LAST:event_viewBagActionPerformed

    private void userLastNameTextBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLastNameTextBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLastNameTextBox1ActionPerformed

    private void addnewBagBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewBagBtnActionPerformed
    Bag newBag = new Bag();

    // Check if any field is empty
    if(bagNameBox.getText().equals("") || 
       bagQtyBox.getText().equals("") || 
       categoryBox1.getSelectedItem()== null || 
       PriceBox.getText().equals("")) {
        JOptionPane.showMessageDialog(rootPane, "Fill all fields");
    }
    else {
            // Parse the input values
            int bagQty = Integer.parseInt(bagQtyBox.getText());
            double bPrice = Double.parseDouble(PriceBox.getText());

            // Set the parsed values to the Bags object
            newBag.setBagQty(bagQty);  // SetBagID should accept int
            newBag.setbName(bagNameBox.getText());
            newBag.setbCategory(categoryBox1.getSelectedItem().toString());
          //  newBag.SetBagCat(bagCategory);
            newBag.setbPrice(bPrice);  // SetBagPrice should accept double

            // Perform the logic to add the bag
            BagAddLogic bAl = new BagAddLogic();
            bAl.AddNewBag(newBag);
            clearData();
        } 
        
    }//GEN-LAST:event_addnewBagBtnActionPerformed

    private void passwordTextBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextBox1ActionPerformed

    private void viewBagButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBagButtonActionPerformed
        // Assuming you have a JTable named bagsTable and a DefaultTableModel named tableModel
        String filePath = "E:\\icbt assignment\\sem2\\sem 2.2\\oop\\AssignmentExample\\bags.txt";
        File file = new File(filePath);

        DefaultTableModel model = (DefaultTableModel) bagTable.getModel();  // Initialize model
        
        model.setRowCount(0);

        try (BufferedReader br = new BufferedReader(new FileReader(file)))  {
        String line;
        while ((line = br.readLine()) != null) {
            String[] dataRow = line.trim().split(",");
            model.addRow(dataRow);
        }

        } 
        catch (FileNotFoundException ex) {
        Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
        Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewBagButtonActionPerformed

    private void PriceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PriceBoxActionPerformed

    private void seaarchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seaarchBtnActionPerformed
        // TODO add your handling code here:
         String filePath = "E:\\icbt assignment\\sem2\\sem 2.2\\oop\\AssignmentExample\\bags.txt";
        File file = new File(filePath);

        DefaultTableModel model = (DefaultTableModel) bagTable2.getModel();  // Initialize model
        model.setRowCount(0);  // Clear the table before displaying new data

    // Get the selected category from the combo box
        String selectedCategory = categoryBox2.getSelectedItem().toString().trim();  

    // Check if the selected category is blank
        if (selectedCategory.isEmpty()) {
        // Show an error message if no category is selected
            JOptionPane.showMessageDialog(null, "Please select a bag category.", "Error", JOptionPane.ERROR_MESSAGE);
        return;  
        }

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line;
        
        while ((line = br.readLine()) != null) {
            String[] dataRow = line.split(",");  // Split by comma to get array elements

            if (dataRow.length > 1) {  // Ensure there are enough elements in the array
                String bagCategory = dataRow[1].trim();  // Bag category is in the third column (index 2)

                // Check if the category matches the selected category
                if (bagCategory.equalsIgnoreCase(selectedCategory)) {
                    model.addRow(dataRow);  // Add row if the category matches
                }
            }
        }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
         }  
    }//GEN-LAST:event_seaarchBtnActionPerformed

    private void categoryBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryBox2ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PriceBox;
    private javax.swing.JLayeredPane UserSignUpPanel1;
    private javax.swing.JMenuItem addBag;
    private javax.swing.JPanel addBagPannel;
    private javax.swing.JButton addNewUserButton1;
    private javax.swing.JMenuItem addNewUserMenuItem;
    private javax.swing.JButton addnewBagBtn;
    private javax.swing.JTextField bagNameBox;
    private javax.swing.JTextField bagQtyBox;
    private javax.swing.JTable bagTable;
    private javax.swing.JTable bagTable2;
    private javax.swing.JComboBox<String> categoryBox1;
    private javax.swing.JComboBox<String> categoryBox2;
    private javax.swing.JTextField confirmPasswordTextBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField passwordTextBox1;
    private javax.swing.JButton seaarchBtn;
    private javax.swing.JMenuItem searchBag;
    private javax.swing.JPanel searchBagPannel;
    private javax.swing.JTextField userFirstNameTextBox1;
    private javax.swing.JTextField userLastNameTextBox1;
    private javax.swing.JTextField usernameTextBox1;
    private javax.swing.JMenuItem viewBag;
    private javax.swing.JButton viewBagButton;
    private javax.swing.JPanel viewBagpannel;
    // End of variables declaration//GEN-END:variables
}
